#cloud-config
coreos:
  - name: rabbitmq.service
    command: start
    enable: true
    content: |
      [Unit]
      Description=RabbitMQ
      After=docker.service
      Requires=docker.service

      [Service]
      TimeoutStartSec=0
      Restart=always
      Environment=
      ExecStartPre=-/usr/bin/docker kill rabbitmq
      ExecStartPre=-/usr/bin/docker rm rabbitmq
      ExecStartPre=/usr/bin/docker pull checkr/rabbitmq-autocluster:3.6.6
      ExecStart=/usr/bin/docker run --name rabbitmq --net=host -p 4369:4369 -p 5672:5672 -p 15672:15672 -p 25672:25672 -e AUTOCLUSTER_TYPE=aws -e AWS_AUTOSCALING=true -e AUTOCLUSTER_CLEANUP=true -e CLEANUP_WARN_ONLY=false -e AWS_DEFAULT_REGION=us-east-1 checkr/rabbitmq-autocluster:3.6.6
      ExecStop=/usr/bin/docker stop -t 10 rabbitmq 

      [Install]
      WantedBy=multi-user.target
